quarkus:
  http:
    port: 8082
  smallrye-openapi:
    path: /q/openapi
    info:
      title: Project Service API
      version: "1.0"
      description: Endpoints for projects/boards/tasks (skeleton)
  swagger-ui:
    always-include: true
