quarkus:
  http:
    port: 8082
  smallrye-openapi:
    path: /q/openapi
    info:
      title: Project Service API
      version: "1.0"
      description: Project management service
  swagger-ui:
    always-include: true
  
  datasource:
    db-kind: postgresql
    username: ${DATASOURCE_USERNAME:taskapp}
    password: ${DATASOURCE_PASSWORD:secret}
    jdbc:
      url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskdb}
  
  hibernate-orm:
    database:
      generation: update