quarkus:
  http:
    port: 8082
    cors:
      ~: true
      origins: "http://localhost:3000"
      headers: "*"
      methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  smallrye-openapi:
    path: /q/openapi
    info:
      title: Project Service API
      version: "1.0"
      description: Project management service
  swagger-ui:
    always-include: true
  
  datasource:
    db-kind: postgresql
    username: ${DATASOURCE_USERNAME:taskapp}
    password: ${DATASOURCE_PASSWORD:secret}
    jdbc:
      url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskdb}
  
  hibernate-orm:
    database:
      generation: update
  
  kafka:
    devservices:
      enabled: false

mp:
  messaging:
    outgoing:
      activity-events:
        connector: smallrye-kafka
        topic: activity-events
        bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: io.quarkus.kafka.client.serialization.JsonbSerializer
      notification-events:
        connector: smallrye-kafka
        topic: notification-events
        bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: io.quarkus.kafka.client.serialization.JsonbSerializer