server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: taskapp
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # dev only, not for prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: user-service

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
