spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskdb}
    username: ${SPRING_DATASOURCE_USERNAME:taskapp}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  security:
    user:
      name: admin
      password: ${SPRING_SECURITY_PASSWORD:admin123}
server:
  port: 8081

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:myVerySecretKeyForJWTTokenGeneration123456789}
  expiration: ${JWT_EXPIRATION:86400000}

# Admin Configuration
admin:
  email: ${ADMIN_EMAIL:admin@taskapp.com}
  password: ${ADMIN_PASSWORD:admin123}

# CORS Configuration
cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
