micronaut:
  application:
    name: notification-service
  server:
    port: 8083
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - http://localhost:3000
          allowed-methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          allowed-headers:
            - "*"
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      static:
        paths: classpath:static
        mapping: /**
mongodb:
  uri: ${MONGO_URI:`mongodb://localhost:27017/notificationdb`}

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumers:
    notification-service:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.micronaut.configuration.kafka.serde.JsonObjectDeserializer
      auto-offset-reset: earliest
      session-timeout: 30000
      heartbeat-interval: 3000
      max-poll-interval: 300000
  health:
    enabled: false

endpoints:
  all:
    enabled: true
    sensitive: false
  openapi:
    enabled: true
    sensitive: false