micronaut:
  application:
    name: notification-service
  server:
    port: 8083

  # Serve generated OpenAPI + Swagger UI as static resources
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      static:
        paths: classpath:static
        mapping: /**

# Enable OpenAPI and Swagger UI
endpoints:
  all:
    enabled: true
    sensitive: false
  openapi:
    enabled: true
    sensitive: false

# Example: (optional) configure Mongo/Slack/etc. later
# notification:
#   slack:
#     webhookUrl: ${SLACK_WEBHOOK_URL:}
