ktor:
  deployment:
    port: ${PORT:8084}
    host: 0.0.0.0
  application:
    modules:
      - org.taskmanagementapp.activity.ApplicationKt.module

mongo:
  uri: ${MONGO_URI:"mongodb://localhost:27017"}
  database: ${MONGO_DB:"activitydb"}
  collection: ${MONGO_COLLECTION:"events"}

kafka:
  bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:"localhost:9092"}
  group.id: ${KAFKA_GROUP_ID:"activity-service"}
  topic: ${KAFKA_TOPIC:"activity-events"}
  auto.offset.reset: ${KAFKA_AUTO_OFFSET_RESET:"earliest"}
